### ISSUE TITLE
Too many warnings clutter example in Reference

### ISSUE THREAD

**Issue by espinielli** [lepennec/ggwordcloud#1]
The examples in `geom_text_wordcloud` generate a huge amount of warnings as seen online
https://lepennec.github.io/ggwordcloud/reference/geom_text_wordcloud.html

**Comment by lepennec** [comment]
Thank you for noticing the issue. This seems to be a text encoding issue triggered by some device, for instance pdf(). I'm investigating.

**Comment by lepennec** [comment]
Regenerating the references in rstudio is sufficient to fix the pkgdown issue. Note that there is indeed a problem with the regular pdf device and utf8 characters, which is not specific to this package.
