### ISSUE TITLE
Mask not performing

### ISSUE THREAD

**Issue by alecgynness** [lepennec/ggwordcloud#10]
Hello,

I love this package and am eternally thankful for your reimplementation in ggplot. 
I have managed to reproduce almost every wordcloud your provide in the vignette except the mask. 

I have struggled with all aspects and cannot seem to get the mask function to work at all. There is no error at all on the console, but the masking is not applied to the resulting cloud. I have also replaced the default hearth.png mask with my own files in /extdata/ but same (lack of) issue.

Could this be something specific to my R install? I did not see this coming up as an outstanding issue, but I noticed a number of folks asking about this on the wordcloud2 forums.

Thanks again for this most excellent package

**Comment by lepennec** [comment]
Can you send me a script and the ouput of `sessionInfo()`? The mask function has not been tested a lot...

**Comment by alecgynness** [comment]
sorry for delay, will try to send shortly.
