### ISSUE TITLE
Cannot display Chinese characters in Mac OS

### ISSUE THREAD

**Issue by ctfysh** [lepennec/ggwordcloud#11]
I use this package with the "love" example and find that the results are both OK in Win10 and Ubuntu 16.04, however when I run the code in Mac OS, the Chinese characters cannot display correctly, they only show polygons. I also use wordcloud package and find the Chinese characters are OK, too. Even I set the text font family in theme function, it doesn't work. Can you tell me how to deal with it? Thank you!

**Comment by lepennec** [comment]
Thank you for your feedback. I'm aware of this kind of issue. Font handling
is something very tricky and I don't have OS X. Do you have the same issue
using the original geom_text ?

PS: Have you seen this ggrepel issue:
https://github.com/slowkow/ggrepel/issues/87
My guess is this is a similar issue than yours...

**Comment by ctfysh** [comment]
Yes, they are the same problem. I use the same method to modify the code, the Chinese character can display correctly while other language characters become polygons with the following code.
```
set.seed(42)
ggplot(love_words_small, aes(label = word)) +
    geom_text_wordcloud(family = "Kai") +
    theme_minimal()
```
So, for multiple languages, which font family should be chosen to this problem?

**Comment by lepennec** [comment]
If I get it correctly, you should either find a font that includes both
latin and chinese characters or use a different font for the two different
cases...

**Comment by aito123** [comment]
I would recommend using Noto Simplified Chinese from Google Fonts to solve the display problem:
Link to the font: https://fonts.google.com/noto/specimen/Noto+Sans+SC

You can use it in R thorugh the package showtext:

```{r}
install.packages(c("showtext", "tidyverse", "ggwordcloud"))
library(showtext)
library(tidyverse)
library(ggwordcloud)

font_add_google("Noto Sans SC", "noto")
showtext_auto()

set.seed(42)
ggplot(love_words_small, aes(label = word)) +
    geom_text_wordcloud(family = "noto") +
    theme_minimal()

```

**Comment by lepennec** [comment]
Thank you for the tip.
