### ISSUE TITLE
Unable to make the colourbar appear

### ISSUE THREAD

**Issue by gvianaf** [lepennec/ggwordcloud#13]
Hello.
First off, thanks for the package, very easy to use and to customize.

There's just one thing that I can't do: make the color legend appear... I've tried many approaches, but it just doesn't want to appear. Is there a way to force it?

Below a small example, using the love words dataset:

library(ggwordcloud)
#> Loading required package: ggplot2
data("love_words_small")
data("love_words")

set.seed(42)
ggplot(love_words_small, aes(label = word, color = speakers)) +
  geom_text_wordcloud() +
  theme_minimal() +
  scale_color_viridis_c(guide = "colourbar")

**Comment by lepennec** [comment]
There is a show.legend option in geom_text_wordcloud to do that:

library(ggwordcloud)

#> Loading required package: ggplot2
data("love_words_small")
data("love_words")

set.seed(42)
ggplot(love_words_small, aes(label = word, color = speakers)) +
geom_text_wordcloud(show.legend = TRUE) +
theme_minimal() +
scale_color_viridis_c()

It took me some time to rediscover it ;-)

**Comment by gvianaf** [comment]
Thanks! I somehow knew I didn't look thoroughly...
