### ISSUE TITLE
wordcloud needs a legend

### ISSUE THREAD

**Issue by PursuitOfDataScience** [lepennec/ggwordcloud#16]
Hi, I used `geom_text_wordcloud_area()` and it works like a charm! One thing I think it needs to have is a legend. This is especially the case when I add `color = something` so that I am able to distinguish which text belongs to which category. Maybe this is more like user suggestion than an issue I can provide after using it. Thanks!

**Comment by lepennec** [comment]
There is a show.legend option that should help you.

**Comment by PursuitOfDataScience** [comment]
Sorry, I didn't pay attention to it. Yes, it works perfect! Thanks!
