### ISSUE TITLE
grouping words by a var in one single cloud?

### ISSUE THREAD

**Issue by coelhocao** [lepennec/ggwordcloud#19]
Hi,

Is there a way to position words grouped by a variable, but in one single cloud? 
Maybe a could with multiple points to gravity?

**Comment by lepennec** [comment]
This can be done manually by specifying an initial position (aesthetics x and y) to each word according to the group. This involves some manual tweaking as the size of each wordcloud is not known at the beginning. There is an example using only the x axis in the vignette.
