### ISSUE TITLE
rationalize for provision of new word data sets

### ISSUE THREAD

**Issue by espinielli** [lepennec/ggwordcloud#2]
World clouds are a nice piece of visualization especially in slides. These usually terminate with a slide like "Thank you" or "Questions?" that could be rendered with a word cloud.
I propose to rationalize the existing infrastructure of the 'Love' word data set to make it easy to add new ones.
This is possible if there are 2 tables such as:

1. language stats table (ISO 639-3 code, L1, L2), and
1. the word dictionary (ISO 639-3 code, word).

**Comment by lepennec** [comment]
Thank you!
