### ISSUE TITLE
Big words appearing on the outside?

### ISSUE THREAD

**Issue by JCSzamosi** [lepennec/ggwordcloud#20]
In your example plots, it appears like the larger words all appear towards the centre of the image and the smaller words are on the periphery. When I try to use this package, I'm finding the opposite: that the larger words are around the periphery and the smaller words are at the centre.

is this something I can change? I'd like to see the larger words near the centre. I've tried relevelling the label factor a few different ways, but it doesn't seem to make a difference.

**Comment by lepennec** [comment]
Hi,
The word are plotted following their order in the data frame. The first
word is positioned at the center and the others wherever they fit following
a spiral.
My guess is thus that if you sort your data frame with the largest
frequencies first you will have what you want.
Yours
Erwan

**Comment by JCSzamosi** [comment]
This worked, thank you!
