### ISSUE TITLE
NA displayed as legend key 

### ISSUE THREAD

**Issue by trekonom** [lepennec/ggwordcloud#21]
Hi Erwan,

when answering [this](https://stackoverflow.com/q/77503820/12993861) question on SO I stumbled over an issue which looks like a bug to me introduced with the new `label_content` aesthetic added in `ggwordcloud 0.6.0`.

When adding a legend to a word cloud the value of `label_content` (which defaults to `NA`) is displayed as the legend key glyph instead of the default `"a"` one would expect from `ggplot2::draw_key_text`. Here is a reprex of the issue:
``` r
library(ggwordcloud)
#> Loading required package: ggplot2

set.seed(42)
data("love_words_latin_small")

p <- ggplot(love_words_latin_small, aes(label = word, size = speakers)) +
  geom_text_wordcloud(show.legend = TRUE) +
  scale_size_area(max_size = 20) +
  theme_minimal()

p
```

![](https://i.imgur.com/FlWrpP9.png)

By default `ggplot2::draw_key_text` sets a letter "a" as the default key glyph by checking the [condition](https://github.com/tidyverse/ggplot2/blob/4f05313b5e3cbfe71c2d3b9e9183780d66439843/R/legend-draw.R#L239):
```
 if(is.null(data$label)) data$label <- "a"
```
However, because of the new `label_content` aes, the data passed from `geom_text_word_cloud` to `draw_key_text` now contains a column named `label_content`. Hence, because `$` does partial matching the check `is.null(data$label)` returns `FALSE` even if there is actually no `label` column (whereas `is.null(data[["label"]])` would return `TRUE`) and more importantly for the same reason the value from the `label_content` column (which by default is `NA`) is used as the label for the legend key.

A workaround would be to set a value for `label` or `label_content` via the `override.aes` argument of `guide_legend`:
``` r
p +
  guides(size = guide_legend(override.aes = list(label_content = "a")))
```

![](https://i.imgur.com/T7QKafr.png)

**Comment by lepennec** [comment]
Thank you for detecting this issue! The best fix in the code is to to use a NULL default value for the label_content...

**Comment by lepennec** [comment]
Can you check that this is working by default with the latest commit?

**Comment by trekonom** [comment]
Thanks for the quick fix. Works fine. Both for the example  I added in the issue as well the one in the SO question.
