### ISSUE TITLE
Chinese Character cannot be shown 

### ISSUE THREAD

**Issue by chenx2018** [lepennec/ggwordcloud#5]
The Chinese Character cannot be shown in the example, I have tried the following:

ggplot(love_words_small, aes(label = word)) +
  geom_text_wordcloud() +
  theme_minimal(base_family = "STKaiti")

Still not work

**Comment by lepennec** [comment]
Using chinese caracter seems to be tricky with R. I have been able to make it work with some pdf writer but not the  classical one from R. I'm still working to understand why...
