### ISSUE TITLE
Cannot  put the biggest word at the center of the word cloud.

### ISSUE THREAD

**Issue by zhanghao-njmu** [lepennec/ggwordcloud#6]
I want to plot a word cloud in which the biggest word  (word sizes are scaled by the column "freq" which represents odds-ratio) is displayed at the center of the picture.  Sometimes geom_text_wordcloud() worked. However, I failed with the data attached to this issue. The result looks like this
![image](https://user-images.githubusercontent.com/24678781/51804180-90ba1b80-2298-11e9-9ad9-cf2347aa371d.png)
How can I make the biggest word such as "PK--M" at the center?
[df.txt](https://github.com/lepennec/ggwordcloud/files/2800268/df.txt)

**Comment by zhanghao-njmu** [comment]
Here is the code I used:
```
ggplot(df, aes(label = word,size=1000-freq,color = -log10(p.adjust),angle = angle)) +
  geom_text_wordcloud(rm_outside = TRUE,eccentricity = 1,shape = "square") +
  scale_size_area(max_size = 24)+
  scale_radius(range = c(0, 20), limits = c(0, NA))+
  gradient_color(brewer.pal(9,"Blues")[c(3,9)])+
  theme_minimal()+theme(aspect.ratio =  0.7)
```

**Comment by lepennec** [comment]
The words are placed in the data.frame order starting from the center. You should thus sort your data.frame for instance with dplyr::arrange.

```
ggplot(dplyr::arrange(df,freq),
           aes(label = word,size=freq,color = -log10(p.adjust),angle = angle)) +
  geom_text_wordcloud(rm_outside = TRUE,eccentricity = 1,shape = "square") +
  scale_size_area(max_size = 16)+
  heme_minimal()+theme(aspect.ratio =  0.7)
```
seems to produce the result you want.
